timezone: America/Chicago
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
  -
    scope:
      path: "_blaster"
    values:
      layout: "game"
      permalink: "/games/blaster/:slug"
      game: "Blaster"
  -
    scope:
      path: "_gemini-rising"
    values:
      layout: "game"
      permalink: "/games/gemini-rising/:slug"
      game: "Gemini Rising"
collections:
  blaster:
    output: true
    permalink: /:collection/:name
  gemini-rising:
    output: true
    permalink: /:collection/:name
highlighter: rouge
