defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "/blaster"
    values:
      layout: "game"
highlighter: rouge
collections:
  blaster:
    output: true
    permalink: /:collection/:name
