defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_blaster"
    values:
      layout: "game"
      permalink: "/games/blaster/:slug"
highlighter: rouge
collections:
  blaster:
    output: true
    permalink: /:collection/:name
