baseURL = "https://drhayes.io/"
languageCode = "en-us"
title = "drhayes.io"
assetDir = "assets"

[permalinks]
  posts = "/:year/:month/:day/:title"


[menu]

  [[menu.main]]
    identifier = "home-link"
    name = "drhayes.io"
    url = "/"
    weight = -10

  [[menu.main]]
    identifier = "blog-link"
    name = "blog"
    url = "/posts"
    weight = -5


[taxonomies]
  tag = "tags"
