baseURL = "https://drhayes.io/"
languageCode = "en-us"
title = "drhayes.io"
assetDir = "assets"

[permalinks]
  posts = "/:year/:month/:day/:title"


[menu]

  [[menu.main]]
    identifier = "home-link"
    name = "drhayes.io"
    url = "/"
    weight = -1
