baseURL = "/"
title = "drhayes.io"
defaultContentLanguage = "en"
theme = "drhayes"
metaDataFormat = "yaml"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110
