baseURL = "https://drhayes.io/"
languageCode = "en-us"
title = "drhayes.io"
assetDir = "assets"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License by David R. Hayes."

pygmentsCodefences = true
pygmentsStyle = "monokai"

[author]
  name = "David R. Hayes"


[permalinks]
  posts = "/:year/:month/:day/:title"


[menu]

  [[menu.main]]
    identifier = "blog-link"
    name = "Blog"
    url = "/posts"
    weight = -5


[taxonomies]
  tag = "tags"
