baseURL = "https://drhayes.io/"
title = "drhayes.io"
defaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsCodeFences = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110
