[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'self'; img-src 'self' *.amazonaws.com *.gravatar.com *.mapbox.com *.omdbapi.com i.ytimg.com i.vimeocdn.com raw.githubusercontent.com  webmention.io i.creativecommons.org; child-src 'self'; frame-ancestors 'none'"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*.jsonld"
  [headers.values]
    Content-Type = "application/ld+json; charset=utf-8"

[[headers]]
  for = "/*.jrd"
  [headers.values]
    Content-Type = "application/jrd+json; charset=utf-8"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

[[redirects]]
  from = "/posts"
  to = "/blog"

[[redirects]]
  from = "/2019/10/25/gemini-rising-ai-goal-oriented-action-planning/"
  to = "/blog/gemini-rising-ai-goap/"

[[redirects]]
  from = "/2019/03/22/gemini-rising-ai-behavior-trees/"
  to = "/blog/gemini-rising-ai-behavior-trees/"

[[redirects]]
  from = "/2019/03/22/gemini-rising-ai-lua-scripting/"
  to = "/blog/gemini-rising-ai-lua-scripting/"

[[redirects]]
  from = "/2019/03/21/gemini-rising-ai-introduction/"
  to = "/blog/gemini-rising-ai-intro/"

[[redirects]]
  from = "/2018/12/12/ha-ha-again-its-hugo/"
  to = "/blog/ha-ha-again-its-hugo/"

[[redirects]]
  from = "/2018/12/06/ha-ha-just-kidding-im-using-nextjs-now/"
  to = "/blog/ha-ha-just-kidding-im-using-nextjs-now/"

[[redirects]]
  from = "/2018/11/24/oh-well-gatsby-it-is/"
  to = "/blog/oh-well-gatsby-it-is/"

[[redirects]]
  from = "/2018/09/14/gemini-rising-the-stats/"
  to = "/blog/gemini-rising-the-stats/"

[[redirects]]
  from = "/2018/09/13/announcing-gemini-rising-my-new-game/"
  to = "/blog/announcing-gemini-rising-my-new-game/"

[[redirects]]
  from = "/2018/09/12/a-new-start/"
  to = "/blog/a-new-start/"

[[redirects]]
  from = "/games/blaster/articles/*"
  to = "/games/blaster/:splat"

[[redirects]]
  from = "/index.xml"
  to = "/feed.xml"

[[redirects]]
  from = "/feed/*"
  to = "/feed.xml"
