version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - run:
          name: Install AWS CLI
          command: sudo pip3 install awscli

      - run: npm install

      # Cache dependencies.
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build the site.
      - run: npm run export

      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ~/repo/out/ s3://drhayes.io --delete
            else
              echo "Not master branch, dry run only"
              ls -larth ~/repo/out/
            fi
