version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

    working_directory: ~/repo
    environment:
      GATSBY_BUILD_DIR: ~/repo/public

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      # Cache dependencies.
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build the site.
      - run: npm build

      # Update the things and install awscli.
      - run: apk add --update python python-dev py-pip build-base
      - run: pip install awscli

      - deploy:
        name: deploy to AWS
        command: |
        if [ "${CIRCLE_BRANCH}" = "master" ]; then
          aws s3 sync $GATSBY_BUILD_DIR \
          s3://drhayes.io --delete
        else
          echo "Not master branch, dry run only"
        fi
