version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/site
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      # Cache dependencies.
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build the site.
      - run: NODE_ENV=production npm run export

      - persist_to_workspace:
          root: ~/
          paths:
            - site


  deploy:
    docker:
      - image: devillex/docker-firebase
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run:
          name: Sanity check
          command: pwd && ls -larth

      - run:
          name: Deploy to firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
