version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/site
    steps:
      - checkout

      - run:
          name: Download Hugo
          command: curl https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.tar.gz -LO

      - run:
          name: Unpack Hugo
          command: tar -xvzf hugo_0.52_Linux-64bit.tar.gz

      # Build the site.
      - run:
          name: Run hugo
          command: HUGO_ENV=production ./hugo -v

      - run:
          name: Sanity check
          command: cat public/css/site.css || true

      - persist_to_workspace:
          root: ~/
          paths:
            - site


  deploy:
    docker:
      - image: devillex/docker-firebase
    working_directory: /tmp/workspace/site
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - run:
          name: Sanity check
          command: pwd && ls -larth

      - run:
          name: Deploy to firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
