name: Does it build?

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: 'latest'

    - name: Install asciidoctor
      run: sudo apt-get install -y asciidoctor

    - name: Build
      run: hugo --gc --minify -v
