name: Cron Build
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the thing
        run: |
          curl -X POST -d {} {{ secrets.NETLIFY_DEPLOY_HOOK }}
