name: Deploy that pig

on:
  push:
    branches:
      - 'beta/**'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --gc --minify -v

    - name: Deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:personalSiteBeta
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'beta.drhayes.io has been deployed.'
