name: Fetch links!
on:
  schedule:
    - cron: "36 */4 * * *"

  workflow_dispatch:

jobs:
  fetchem:
    name: Fetch those links
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22.2.0"

      - name: Install the libraries
        run: npm install

      - name: Run the get-links script
        env:
          PINBOARD_API_TOKEN: ${{ secrets.PINBOARD_API_TOKEN }}
        run: npm run get-links

      - name: Update repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Creating link posts

      - name: Build and maybe send webmentions
        run: npm run build
